[project]
name = "wordle-py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "fastapi>=0.115.12",
    "pydantic>=2.10.6",
    "sqlalchemy>=2.0.40",
    "uvicorn>=0.34.0",
]
